---
title: "Agency Finder Enhancements-Phase 2"
output: html_notebook
---


```{r}

Transportation_policy<-read_excel("C:/Users/madhu/OneDrive/Documents/Ready for school, ready for life/Agency Finder/Transportation Policy with Program ID.xls.xlsx")


```





```{r}
Transportation_policy <- subset(Transportation_policy, select = c(`Program: Program Name`, `Program: ID`,`Evidence Based`,`Services Provided in Other Languages`,`Services Provided in Other Lang Yes/No`,`Transportation Policy`))

```


```{r}
View(Transportation_policy)

```




```{r}
Transportation_policy$`Services Provided in Other Lang Yes/No` <- ifelse(grepl("Bilingual staff on-site|Spanish interperters|Spanish|yes|Yes", Transportation_policy$`Services Provided in Other Languages`), "yes",ifelse(grepl("NA|no|No|N/A", Transportation_policy$`Services Provided in Other Languages`), "no", "")  )
```




```{r}
View(Transportation_policy)

```

```{r}
Transportation_policy$`Transportation Policy Yes/No`<- ifelse(grepl("Yes|yes|Only for field trips|Must have bus fair card or pay once you reach the bus|IHAP is not able to transport clients, but will assist clients with accessing transportation resources such as Medicaid, Orange Card, or Senior Resources transportation.", Transportation_policy$`Transportation Policy`), "yes",ifelse(grepl("NA|No|None|N/A", Transportation_policy$`Transportation Policy`), "no", "")  )
```


```{r}
library("writexl")
```

#Extracting Master_Program_List dataframe 

```{r}
write_xlsx(Transportation_policy,"C:/Users/madhu/OneDrive/Documents/Ready for school, ready for life/AgencyListDedupe/Transportation_policyx`.xlsx")
```

